### PR TITLE
I forgot to update the peer dep, sorry :roll_eyes:

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
Ping @alexjeffburke :)

**Comment by papandreou** [comment]
Pingpingpingping @alexjeffburke 😆

**Comment by alexjeffburke** [comment]
Argh, I don’t know how I missed this. Will get it out next I’m by my keyboard!

**Comment by alexjeffburke** [comment]
Not sure why this didn't close itself - landed as 97d203cbd70a45ae2e3397793cf378e3c1858369.

**Comment by papandreou** [comment]
Thanks 🤗

**Pull request closed without merging**
